version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    restart: unless-stopped

